### ISSUE TITLE
Request: Internals of Vue

### ISSUE THREAD

**Issue by znck** [znck/vue-bangalore#9]
An overview of reactivity system of Vue.

**Comment by nshntarora** [comment]
Hey! I'd love to take this up. Can you share more details on what you expect from this talk?

**Comment by znck** [comment]
Most interesting topic is reactivity system (dependency tracking, change propagation, computed properties, re-rendering etc). If you need any assistance or resources, write to me (hi@znck.me).

Alternatively you talk about template compilation, DOM updates, vdom, diff & patch etc but above one would be better.

**Comment by znck** [comment]
Find in https://github.com/znck/vue-bangalore/commit/b4afa23d04ca5a8b9729cacf362cd032914803ef
